{
 "title": "Pods",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_info{container!=\"istio-proxy\",namespace=~\"$namespace\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"istio-proxy\",namespace=~\"$namespace\",container!=\"\"}) by (container) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container!=\"istio-proxy\",namespace=~\"$namespace\",container!=\"\"}[5m])) by (container)",
     "legendFormat": "总核数"
    },
    {
     "expr": "kube_pod_container_status_running{container!=\"istio-proxy\",namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"istio-proxy\",namespace=~\"$namespace\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\",container!=\"istio-proxy\",namespace=~\"$namespace\"}) by (container) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container!=\"istio-proxy\",namespace=~\"$namespace\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container!=\"istio-proxy\",namespace=~\"$namespace\"} / (1024*1024)) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  }
 ]
}